# Which blocks do you want to be denied from being broken
# This uses item ID's to check which block, get them here
# http://minecraft.gamepedia.com/Data_values/Block_IDs
breaking:
  blacklistedblocks:
    - 1
    - 2
    - 3
    - 4

# Which blocks do you want to be denied from being placed
# This uses item ID's to check which block, get them here
# http://minecraft.gamepedia.com/Data_values/Block_IDs
placing:
  denymessage:
    enabled: true
    message: "&c&lHEY! &7You cannot place this block!"
  blacklistedblocks:
    - 1
    - 2
    - 3
    - 4
  
# Used for items that cannot be used 
# In the blacklisted-blocks section.
other:
  disablebuckets: false