# Which blocks do you want to be denied from being broken
# This uses item ID's to check which block, get them here
# http://minecraft.gamepedia.com/Data_values/Block_IDs
breaking:
  blacklistedblocks:
    - 1
    - 2
    - 3
    - 4

# Which blocks do you want to be denied from being placed
# This uses item ID's to check which block, get them here
# http://minecraft.gamepedia.com/Data_values/Block_IDs
placing:
  blacklistedblocks:
    - 1
    - 2
    - 3
    - 4

# Changing this does
# Nothing at all :P
chathandler:
  enabled: false
  sentmessage: false